"""Add expires_at fields to token

Revision ID: 96de45e03ee1
Revises: dd3db0e8eff4
Create Date: 2025-09-02 08:43:21.538082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96de45e03ee1'
down_revision: Union[str, Sequence[str], None] = 'dd3db0e8eff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('token', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'expires_at')

    # ### end Alembic commands ###
