"""fix expires_at default to None

Revision ID: cf7d8c80a925
Revises: 96de45e03ee1
Create Date: 2025-09-02 14:38:21.720237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7d8c80a925'
down_revision: Union[str, Sequence[str], None] = '96de45e03ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'token',
    'expires_at',
    existing_type=sa.DateTime(),
    nullable=True,
    server_default=None
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'token', 'expires_at',
    existing_type=sa.DateTime(),
    nullable=True,
    server_default=sa.text('0')
)
    # ### end Alembic commands ###
