"""Add is_superuser fields to users

Revision ID: dd3db0e8eff4
Revises: 6bbaf7672528
Create Date: 2025-08-30 08:45:03.812660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3db0e8eff4'
down_revision: Union[str, Sequence[str], None] = '6bbaf7672528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')

    # ### end Alembic commands ###
